# Generated by Django 4.2.2 on 2023-06-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
