# Generated by Django 4.2.2 on 2023-06-21 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('CONTRIBUTOR_PERMISSION', 'contributorsPermission'), ('AUTHOR_PERMISSION', 'authorPermission')], max_length=25)),
                ('role', models.CharField(choices=[('CONTRIBUTOR', 'contributor'), ('AUTHOR', 'author')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=128, verbose_name='titreproject')),
                ('description', models.CharField(max_length=2048, verbose_name='descriptionproject')),
                ('type', models.CharField(choices=[('FRONTEND', 'Front-end'), ('BACKEND', 'Back-end'), ('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=16)),
                ('author_user_id', models.ManyToManyField(related_name='contributs', through='projectsManager.Contributors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('issue_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=128, verbose_name='titreissue')),
                ('desc', models.CharField(max_length=2048, verbose_name='descriptionissue')),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('IMPROVEMENT', 'Improvement'), ('TASK', 'Task')], max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=12)),
                ('status', models.CharField(choices=[('TODO', 'To-do'), ('WIP', 'WIP'), ('DONE', 'Done')], max_length=12)),
                ('assignee_user_id', models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, related_name='issue_assignee', to=settings.AUTH_USER_MODEL)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projectsManager.project')),
            ],
        ),
        migrations.AddField(
            model_name='contributors',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsManager.project'),
        ),
        migrations.AddField(
            model_name='contributors',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=2048, verbose_name='descriptioncomment')),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projectsManager.issue')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together={('user_id', 'project_id')},
        ),
    ]
